[project]
name = "tempo"
version = "0.1.0"
description = "A Python-based web scraper for the Indonesian news website tempo.co"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests>=2.31.0",
    "beautifulsoup4>=4.12.0",
    "lxml>=4.9.0",
    "python-dotenv>=1.0.0",
]
